// Generated by tools/build_levels.py -- edit that file instead.
const LEVELS = [
  [
      "                                                                                                                                                                                                                    ",
      "                                                                                                                                                                                                                    ",
      "                                                                                                                                                                                                                    ",
      "                                                                                                                                                                                                                    ",
      "                                                                                                                                                                                                                    ",
      "                      ?o                                 ooo                             o                                                                                                       S                  ",
      "                                                                  oo                    BBB    oo                                                                                               SS                  ",
      "                                                                     oo                       ====                       oo                              o o                                   SSS                  ",
      "                                                                    ====                                                              oo                =====                                 SSSS                  ",
      "                ?   BoB?B                     PP        BBMBB   ==          B?B       ?               BB?BB       ?M?                S  S         B?B?B               ?                      SSSSS                  ",
      "                                      PP      PP                                                                        BBBB        SS  SS                                  PP      oooo    SSSSSS                  ",
      "                            PPg       PP   g  PP          g   k               g     g                   k     gg              g    SSS  SSS     k                 gg        PP  g          SSSSSSS                  ",
      "                            PP        PP      PP                                                                                  SSSS  SSSS                                PP            SSSSSSSS     F            ",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  ],
  [
      "                                                                                                                                                                                              ",
      "                                                                                                                                                                                              ",
      "                                                                                                                                                                                              ",
      "                                                                                                                                                                                              ",
      "                                 ooo                                                                                                                                                          ",
      "           o                                                                                                   o                                                             S                ",
      "                                                                                         oooo                 ===                                                           SS                ",
      "                                                    B?B                      oo                                          ooo                                               SSS                ",
      "                        PP      BBMBB                         o             S   S       ======                                                  BB?BB   o                 SSSS                ",
      "          ?B?           PP                o                 =====          SS   SS                      B?BMB                     ?     PP            =====              SSSSS                ",
      "                  PP    PP              =====                             SSS   SSS                                     ======          PP                              SSSSSS                ",
      "              g   PP    PP  k                   gg                  k    SSSS   SSSS              ggg               k               g   PP    k                 gg     SSSSSSS                ",
      "                  PP    PP                                              SSSSS   SSSSS                                                   PP                            SSSSSSSS      F         ",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  ]
];
