"""Composes the level layouts in levels.js from a compact feature description.

Run: python3 tools/build_levels.py
Rows are 15 tiles tall; row 13 and 14 are the default ground surface.
"""
import json
import os

H = 15
GROUND_TOP = 13


class Level:
    def __init__(self, width, gaps=()):
        self.width = width
        self.grid = [[" "] * width for _ in range(H)]
        for x in range(width):
            if any(a <= x < b for a, b in gaps):
                continue
            self.grid[GROUND_TOP][x] = "X"
            self.grid[GROUND_TOP + 1][x] = "X"

    def put(self, x, y, ch):
        self.grid[y][x] = ch

    def row(self, x0, y, s):
        for i, ch in enumerate(s):
            if ch != ".":
                self.grid[y][x0 + i] = ch

    def pipe(self, x, height):
        for i in range(height):
            y = GROUND_TOP - 1 - i
            self.grid[y][x] = "P"
            self.grid[y][x + 1] = "P"

    def stairs(self, x0, height, descending=False):
        for i in range(height):
            col = x0 + i
            top = GROUND_TOP - (height - i if descending else i + 1)
            for y in range(top, GROUND_TOP):
                self.grid[y][col] = "S"

    def dump(self):
        return ["".join(r) for r in self.grid]


def level_one():
    lv = Level(212, gaps=[(68, 72), (94, 98), (152, 157)])
    lv.row(16, 9, "?")
    lv.row(20, 9, "B?B?B")
    lv.row(22, 5, "?")
    lv.put(21, 9, "o")
    lv.put(23, 5, "o")
    lv.pipe(28, 2)
    lv.pipe(38, 3)
    lv.pipe(46, 4)
    lv.put(30, 11, "g")
    lv.put(43, 11, "g")
    lv.row(56, 9, "BBMBB")
    lv.row(57, 5, "ooo")
    lv.put(58, 11, "g")
    lv.put(62, 11, "k")
    lv.row(64, 9, "==")
    lv.row(68, 8, "====")
    lv.row(66, 6, "oo")
    lv.put(69, 7, "o")
    lv.put(70, 7, "o")
    lv.row(76, 9, "B?B")
    lv.put(78, 11, "g")
    lv.put(84, 11, "g")
    lv.row(86, 9, "?")
    lv.row(88, 6, "BBB")
    lv.row(89, 5, "o")
    lv.row(94, 7, "====")
    lv.put(95, 6, "o")
    lv.put(96, 6, "o")
    lv.row(102, 9, "BB?BB")
    lv.put(104, 11, "k")
    lv.put(110, 11, "g")
    lv.put(111, 11, "g")
    lv.row(114, 9, "?M?")
    lv.row(120, 10, "BBBB")
    lv.row(121, 7, "oo")
    lv.put(126, 11, "g")
    lv.stairs(130, 4)
    lv.stairs(136, 4, descending=True)
    lv.put(134, 8, "o")
    lv.put(135, 8, "o")
    lv.put(144, 11, "k")
    lv.row(146, 9, "B?B?B")
    lv.row(152, 8, "=====")
    lv.put(153, 7, "o")
    lv.put(155, 7, "o")
    lv.put(162, 11, "g")
    lv.put(163, 11, "g")
    lv.row(166, 9, "?")
    lv.pipe(172, 3)
    lv.put(176, 11, "g")
    lv.row(180, 10, "oooo")
    lv.stairs(186, 8)
    lv.put(199, GROUND_TOP - 1, "F")
    return lv


def level_two():
    lv = Level(190, gaps=[(40, 45), (60, 64), (88, 93), (120, 126), (150, 154)])
    lv.row(10, 9, "?B?")
    lv.put(11, 5, "o")
    lv.put(14, 11, "g")
    lv.pipe(18, 3)
    lv.pipe(24, 5)
    lv.put(28, 11, "k")
    lv.row(32, 8, "BBMBB")
    lv.row(33, 4, "ooo")
    lv.row(40, 10, "=====")
    lv.put(42, 9, "o")
    lv.put(48, 11, "g")
    lv.put(49, 11, "g")
    lv.row(52, 7, "B?B")
    lv.row(60, 9, "=====")
    lv.put(62, 8, "o")
    lv.put(68, 11, "k")
    lv.stairs(72, 5)
    lv.stairs(80, 5, descending=True)
    lv.put(77, 7, "o")
    lv.put(78, 7, "o")
    lv.row(88, 8, "======")
    lv.row(89, 6, "oooo")
    lv.put(98, 11, "g")
    lv.put(99, 11, "g")
    lv.put(100, 11, "g")
    lv.row(104, 9, "B?BMB")
    lv.row(110, 6, "===")
    lv.put(111, 5, "o")
    lv.put(116, 11, "k")
    lv.row(120, 10, "======")
    lv.row(121, 7, "ooo")
    lv.row(130, 9, "?")
    lv.put(132, 11, "g")
    lv.pipe(136, 4)
    lv.put(142, 11, "k")
    lv.row(144, 8, "BB?BB")
    lv.row(150, 9, "=====")
    lv.put(152, 8, "o")
    lv.put(160, 11, "g")
    lv.put(161, 11, "g")
    lv.stairs(166, 8)
    lv.put(180, GROUND_TOP - 1, "F")
    return lv


def main():
    levels = [level_one().dump(), level_two().dump()]
    out = os.path.join(os.path.dirname(__file__), "..", "levels.js")
    body = ",\n".join(
        "  " + json.dumps(rows, indent=4).replace("\n", "\n  ") for rows in levels
    )
    with open(out, "w") as fh:
        fh.write("// Generated by tools/build_levels.py -- edit that file instead.\n")
        fh.write("const LEVELS = [\n" + body + "\n];\n")
    print("wrote", os.path.abspath(out))


if __name__ == "__main__":
    main()
